"use strict";

const { describe, it, afterEach } = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const createTheme = require("../scripts/create-theme");

const cleanupDirs = [];

function makeTmpDir() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "clawd-create-theme-"));
  cleanupDirs.push(dir);
  return dir;
}

afterEach(() => {
  while (cleanupDirs.length) {
    fs.rmSync(cleanupDirs.pop(), { recursive: true, force: true });
  }
});

describe("create-theme defaults", () => {
  it("resolves the platform-specific user themes directory", () => {
    assert.strictEqual(
      createTheme.getDefaultThemesRoot("win32", { APPDATA: "C:\\Users\\Ruller\\AppData\\Roaming" }, "C:\\Users\\Ruller"),
      path.win32.join("C:\\Users\\Ruller\\AppData\\Roaming", "clawd-on-mobile", "themes")
    );
    assert.strictEqual(
      createTheme.getDefaultThemesRoot("darwin", {}, "/Users/ruller"),
      "/Users/ruller/Library/Application Support/clawd-on-mobile/themes"
    );
    assert.strictEqual(
      createTheme.getDefaultThemesRoot("linux", { XDG_CONFIG_HOME: "/tmp/config-home" }, "/home/ruller"),
      "/tmp/config-home/clawd-on-mobile/themes"
    );
  });

  it("slugifies theme ids into filesystem-safe names", () => {
    assert.strictEqual(createTheme.slugifyThemeId("Pixel Cat!"), "pixel-cat");
    assert.strictEqual(createTheme.slugifyThemeId("   "), "my-theme");
  });
});

describe("create-theme parseArgs", () => {
  it("parses --help", () => {
    const opts = createTheme.parseArgs(["--help"]);
    assert.strictEqual(opts.help, true);
  });

  it("parses -h", () => {
    const opts = createTheme.parseArgs(["-h"]);
    assert.strictEqual(opts.help, true);
  });

  it("parses theme id", () => {
    const opts = createTheme.parseArgs(["pixel-cat"]);
    assert.strictEqual(opts.themeId, "pixel-cat");
  });

  it("parses --name", () => {
    const opts = createTheme.parseArgs(["--name", "My Theme"]);
    assert.strictEqual(opts.name, "My Theme");
  });

  it("parses --author", () => {
    const opts = createTheme.parseArgs(["--author", "Ruller"]);
    assert.strictEqual(opts.author, "Ruller");
  });

  it("parses --target", () => {
    const opts = createTheme.parseArgs(["--target", "/tmp/themes/my"]);
    assert.strictEqual(opts.targetDir, "/tmp/themes/my");
  });

  it("parses combined args", () => {
    const opts = createTheme.parseArgs(["cat", "--name", "Cat", "--author", "Me"]);
    assert.strictEqual(opts.themeId, "cat");
    assert.strictEqual(opts.name, "Cat");
    assert.strictEqual(opts.author, "Me");
  });

  it("throws on unknown option", () => {
    assert.throws(() => createTheme.parseArgs(["--unknown"]), /Unknown option/);
  });

  it("throws on missing value for --name", () => {
    assert.throws(() => createTheme.parseArgs(["--name"]), /Missing value/);
  });

  it("throws on missing value for --name when followed by another flag", () => {
    assert.throws(() => createTheme.parseArgs(["--name", "--author", "test"]), /Missing value/);
  });

  it("throws on extra positional arg", () => {
    assert.throws(() => createTheme.parseArgs(["first", "second"]), /Unexpected extra/);
  });
});

describe("create-theme resolveTarget", () => {
  it("uses targetDir when provided", () => {
    const tmpDir = makeTmpDir();
    const targetDir = path.join(tmpDir, "cat");
    const result = createTheme.resolveTarget({ targetDir });
    assert.strictEqual(result.themeId, "cat");
    assert.strictEqual(result.themesRoot, tmpDir);
    assert.strictEqual(result.autoGeneratedId, false);
  });

  it("uses themeId when provided", () => {
    const result = createTheme.resolveTarget({ themeId: "dog", themesRoot: "/tmp/themes" });
    assert.strictEqual(result.themeId, "dog");
    assert.strictEqual(result.autoGeneratedId, false);
  });

  it("auto-generates id when no themeId", () => {
    const tmpDir = makeTmpDir();
    const result = createTheme.resolveTarget({ themesRoot: tmpDir });
    assert.strictEqual(result.themeId, "my-theme");
    assert.strictEqual(result.autoGeneratedId, true);
  });

  it("auto-increments id when my-theme exists", () => {
    const tmpDir = makeTmpDir();
    fs.mkdirSync(path.join(tmpDir, "my-theme"));
    const result = createTheme.resolveTarget({ themesRoot: tmpDir });
    assert.strictEqual(result.themeId, "my-theme-2");
  });
});

describe("create-theme formatHelp", () => {
  it("contains usage info", () => {
    const help = createTheme.formatHelp();
    assert.match(help, /Usage:/);
    assert.match(help, /--name/);
    assert.match(help, /--author/);
  });
});

describe("create-theme humanizeThemeId", () => {
  it("capitalizes parts", () => {
    assert.strictEqual(createTheme.humanizeThemeId("pixel-cat"), "Pixel Cat");
  });

  it("handles empty input", () => {
    assert.strictEqual(createTheme.humanizeThemeId(""), "My Theme");
  });
});

describe("create-theme guessAuthor", () => {
  it("uses CLAWD_THEME_AUTHOR", () => {
    assert.strictEqual(createTheme.guessAuthor({ CLAWD_THEME_AUTHOR: "Bob" }), "Bob");
  });

  it("falls back to GIT_AUTHOR_NAME", () => {
    assert.strictEqual(createTheme.guessAuthor({ GIT_AUTHOR_NAME: "Git User" }), "Git User");
  });

  it("falls back to USERNAME", () => {
    assert.strictEqual(createTheme.guessAuthor({ USERNAME: "WinUser" }), "WinUser");
  });

  it("falls back to default", () => {
    assert.strictEqual(createTheme.guessAuthor({}), "Your Name");
  });
});

describe("create-theme scaffold", () => {
  it("copies the template and patches theme metadata", () => {
    const themesRoot = makeTmpDir();
    const result = createTheme.createThemeScaffold({
      themeId: "Pixel Cat",
      name: "Pixel Cat",
      author: "Ruller",
      themesRoot,
    });

    assert.strictEqual(result.themeId, "pixel-cat");
    assert.ok(fs.existsSync(path.join(result.targetDir, "theme.json")));
    assert.ok(fs.existsSync(path.join(result.targetDir, "assets", "idle-follow.svg")));

    const themeJson = fs.readFileSync(path.join(result.targetDir, "theme.json"), "utf8");
    assert.match(themeJson, /"name": "Pixel Cat"/);
    assert.match(themeJson, /"author": "Ruller"/);
    assert.doesNotMatch(themeJson, /"license"\s*:/);
  });

  it("auto-picks a fresh my-theme-N id when no theme id is provided", () => {
    const themesRoot = makeTmpDir();
    fs.mkdirSync(path.join(themesRoot, "my-theme"), { recursive: true });

    const result = createTheme.createThemeScaffold({
      themesRoot,
      env: { USERNAME: "Codex" },
    });

    assert.strictEqual(result.themeId, "my-theme-2");
    assert.strictEqual(result.author, "Codex");
    assert.ok(fs.existsSync(path.join(result.targetDir, "theme.json")));
  });

  it("rejects explicit theme ids that already exist", () => {
    const themesRoot = makeTmpDir();
    fs.mkdirSync(path.join(themesRoot, "pixel-cat"), { recursive: true });

    assert.throws(
      () => createTheme.createThemeScaffold({ themeId: "pixel-cat", themesRoot }),
      /already exists/
    );
  });
});
